### ISSUE TITLE
Full Screen Spans Across Both Monitors

### ISSUE THREAD

**Issue by Simmonz** [retux-game/retux#2]
When I choose the full screen option in the options menu it spans the game across both of my two monitors instead of just using the full screen of my primary monitor. I am using version 1.4.1 on Linux. I tried taking a screnshot but the system would only screenshot it when in windowed mode which wouldn't help.

Intel I7-4770 |16GB DDR3-2133 CL9 | Intel HD 4600 1536MB | Mesa 18.3.6 | PureOS 9.0 | Mate 1.20.0 | Kernel 5.10.20-gnu | Acer HA220Q 1920x1080 @ 75hz | HP E221i 1920*1080 @ 60hz

**Comment by onpon4** [comment]
This would be a bug in Pygame. Do you have Pygame 1 or 2?

🕵️

**Comment by Simmonz** [comment]
> This would be a bug in Pygame. Do you have Pygame 1 or 2?
> 
> detective

So I also tested it on my Manjaro system as well and had the same issue. On the Manjaro system the version of Pygame installed is 2.0.1. On PureOS the version installed is 1.9.4 according to Synaptic.

AMD Ryzen 5 2600X | 16GB DDR4-3000 CL15 | MSI RX 580 8GB Gaming X | Mesa 20.3.4 | Manjaro 20.2.1 | Mate 1.24.1 | Kernel 5.11.1-1-MANJARO | AOC G2460P 1920*1080 @ 144hz | HP E221i 1920*1080 @ 60hz

**Comment by onpon4** [comment]
Ok. There's one thing you can try:

1. Get the latest ReTux source code from the main branch: https://github.com/retux-game/retux/archive/main.zip
2. Get the latest SGE source code from its main branch, and install it manually: https://github.com/python-sge/sge/archive/main.zip
3. Try running that ReTux download and see if the problem persists.

I suspect this is an issue that I can't fix; Pygame doesn't give any control over how fullscreen is done, it only allows resolution to be set or not set. But I think SGE 2 changes to allowing Pygame to implicitly determine screen resolution, so maybe the result will be different.

If this doesn't change anything, make sure the problem still persists in the latest Pygame release, and if so, I would suggest filing a bug report with them: https://github.com/pygame/pygame/issues

For filing a bug report with them, I would suggest using one of Pygame's own included examples as a reference, since ReTux's source code is much more complex. I would suggest "aliens.py", which can be switched to fullscreen with the F key.

🕵️

**Comment by onpon4** [comment]
Setting the label on this bug to "invalid" because it's not actually a bug in ReTux per se, it's a bug in Pygame. That said I'm leaving this open until an issue is reported to the proper place or I see confirmation that the latest Pygame fixes this, because I definitely want this fixed.

🕵️

**Comment by Simmonz** [comment]
Alright so here is the news I have. I got the source version of Retux working correctly with fullscreen. I installed the latest SGE from the link you provided  but I think I was missing some dependicies as Retux kept crashing on launch (the source version, 1.4.1 worked fine launch wise). I had to input the following to get it running:

pip install xsge_tiled
pip install xsge_physics
pip install xsge_path
pip install xsge_lighting

The example "aliens.py" also works with fullscreen now. Version 1.4.1 still has the fullscreen issue. Given what I have told you should I still open an issue with Pygame ?

**Comment by onpon4** [comment]
Hmmmmm Ok, that's peculiar. Maybe we should make a simpler test case tomorrow to see what a simple trigger for the bug might be. It might be from the thingy that shows current resolution being buggy.

One thing you can try doing is opening a Python console and doing

```py
import pygame
info = pygame.display.Info()
print(info.current_w, info.current_h)
```

And seeing what it reports as your current screen resolution. That might be the source of the bug.

Ah, and yes, the xsge stuff is requirements to. 😅

🕷️

**Comment by Simmonz** [comment]
> Hmmmmm Ok, that's peculiar. Maybe we should make a simpler test case tomorrow to see what a simple trigger for the bug might be. It might be from the thingy that shows current resolution being buggy.
> 
> One thing you can try doing is opening a Python console and doing
> 
> ```python
> import pygame
> info = pygame.display.Info()
> print(info.current_w, info.current_h)
> ```
> 
> And seeing what it reports as your current screen resolution. That might be the source of the bug.
> 
> Ah, and yes, the xsge stuff is requirements to. sweat_smile
> 
> spider

Here is a copy/paste of my python terminal:

$ python
Python 3.9.1 (default, Feb  6 2021, 06:49:13) 
[GCC 10.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pygame
pygame 2.0.1 (SDL 2.0.14, Python 3.9.1)
Hello from the pygame community. https://www.pygame.org/contribute.html
>>> info = pygame.display.Info()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
pygame.error: video system not initialized
>>> pygame.init()
(7, 0)
>>> info = pygame.display.Info()
>>> print(info.current_w, info.current_h)
1920 1080

**Comment by onpon4** [comment]
Hm, so it's reporting the right size...

I wonder if the problem is specifically with specifying the resolution. Ok, here's a thought, some time ago I made a small test case for the Pygame project for an unrelated bug, here:

[test.zip](https://github.com/retux-game/retux/files/6099622/test.zip)

Can you try running that and pressing F11 to switch to fullscreen? I'm curious if that causes you to have the same issue.

🕵️

**Comment by Simmonz** [comment]
> Hm, so it's reporting the right size...
> 
> I wonder if the problem is specifically with specifying the resolution. Ok, here's a thought, some time ago I made a small test case for the Pygame project for an unrelated bug, here:
> 
> [test.zip](https://github.com/retux-game/retux/files/6099622/test.zip)
> 
> Can you try running that and pressing F11 to switch to fullscreen? I'm curious if that causes you to have the same issue.
> 
> detective

When I presseed F11 on that test it displayed to fullscreen on my main monitor without any issue.

**Comment by onpon4** [comment]
Odd... I'm pretty sure that test script shares the only difference between previous SGE versions and the SGE 2.0 snapshot...

Ok, I've got nothing on what's going on here, but I think we should expedite the release of SGE 2.0 if in fact just switching to that fixes the problem. I'm gonna try to make a release today and also make a corresponding ReTux release.

🕵️

**Comment by onpon4** [comment]
Ah, forgot about this.

New release has been made and this bug should not affect the new release.

🕵️
